name: nix-macos-nix-fix

on: [push, pull_request]

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - run: csrutil disable
      continue-on-error: true
    - run: sudo mkdir -m 0755 /nix && chown runner /nix
      continue-on-error: true
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v3
    - name: Setup repo
      run: |
        git submodule init && git submodule update
    - uses: cachix/cachix-action@v2
      with:
        name: hasktorch
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
